//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEMAttendance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mlrmsEntities : DbContext
    {
        public mlrmsEntities()
            : base("name=mlrmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<device> device { get; set; }
        public virtual DbSet<eletricmeterstatistics> eletricmeterstatistics { get; set; }
        public virtual DbSet<heatmeterstatistics> heatmeterstatistics { get; set; }
        public virtual DbSet<serialservice> serialservice { get; set; }
        public virtual DbSet<sysadmin> sysadmin { get; set; }
        public virtual DbSet<watermeterstatistics> watermeterstatistics { get; set; }
    }
}
