//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEMAttendance
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class serialservice
    {
        [DisplayName("串口服务器编号")]
        [RegularExpression(@"^[0-9a-zA-Z_]+$", ErrorMessage = "串口服务器编号只能由数字、字母或下划线组成")]
        [Required(ErrorMessage = "串口服务器编号不能为空")]
        [StringLength(30, ErrorMessage = "长度不能超过30个字符")]
        public string code { get; set; }

        [DisplayName("端口数量")]
        [RegularExpression(@"^[1-9]$|^1\d$|^2\d$|^3[0]$", ErrorMessage ="端口数量只能为1-30之间的正整数")]
        [Required(ErrorMessage ="端口数量不能为空")]
        public int portcount { get; set; }

        [DisplayName("设备名称")]
        [Required(ErrorMessage = "设备名称不能为空")]
        [StringLength(30, ErrorMessage = "长度不能超过30个字符")]
        [RegularExpression(@"^[a-zA-Z0-9_\u4e00-\u9fa5]+$", ErrorMessage = "串口服务器名称只能由数字、字母、汉字或下划线组成")]
        public string name { get; set; }
    }
}
