//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEMAttendance.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mltynEntities : DbContext
    {
        public mltynEntities()
            : base("name=mltynEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<device> devices { get; set; }
        public virtual DbSet<eletricmeterstatistic> eletricmeterstatistics { get; set; }
        public virtual DbSet<heatmeterstatistic> heatmeterstatistics { get; set; }
        public virtual DbSet<hmbinding> hmbindings { get; set; }
        public virtual DbSet<sysadmin> sysadmins { get; set; }
        public virtual DbSet<watermeterstatistic> watermeterstatistics { get; set; }
    }
}
