//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEMAttendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysadmin
    {
        public long AdminID { get; set; }
        public string AdminCode { get; set; }
        public string AdminName { get; set; }
        public string AdminPwd { get; set; }
        public sbyte AdminType { get; set; }
        public byte[] AdminTemplate { get; set; }
        public byte[] AdminEyeImage { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
